FROM nualartlee/nginx-certbot

# To configure a site create a .conf file in the nginx folder.
COPY *.conf /etc/nginx/conf.d/

# Custom nginx configuration
COPY default/nginx.conf /etc/nginx/nginx.conf
